POST http://localhost:5000/api/parkOfficers/2/protocols   HTTP/1.1
Content-Type: application/json

{
 "serviceNotes": "This is protocol 44",
 "fineAmount": 400.00,
 "violatorFullName": "Den Denovich",
 "violatorPassportNumber": "AB223344"
}