POST http://localhost:5000/api/parkOfficers/17/protocols   HTTP/1.1
Content-Type: application/json

{
 "serviceNotes": "This is protocol 45",
 "fineAmount": 500.00,
 "violatorFullName": "Len Lenovich",
 "violatorPassportNumber": "AB223345"
}